services:
  mysqldb:
    image: mysql:8.0
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQLDB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 20s
      retries: 10

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: .
    env_file: .env
    ports:
      - "${APP_LOCAL_PORT}:${APP_DOCKER_PORT}"
    environment:
          SPRING_APPLICATION_JSON: '{
              "spring.datasource.url": "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?serverTimezone=UTC",
              "spring.datasource.username": "${MYSQLDB_USERNAME}",
              "spring.datasource.password": "${MYSQLDB_ROOT_PASSWORD}",
              "spring.jpa.hibernate.ddl-auto": "update"
            }'
    networks:
    - app-network
volumes:
    mysql-data:

networks:
      app-network:
        driver: bridge